<Project>

  <PropertyGroup>
    <Configuration Condition="'$(Configuration)' == ''">Debug</Configuration>
    <RepositoryRootDirectory>$(MSBuildThisFileDirectory)</RepositoryRootDirectory>
    <BinDir>$(RepositoryRootDirectory)Build</BinDir>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <PropertyGroup>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)\README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

  <PropertyGroup>
    <VeldridSpirvVersion>1.0.14</VeldridSpirvVersion>
    <NativeLibraryLoaderVersion>1.0.13</NativeLibraryLoaderVersion>
    <VorticeWindowsVersion>2.4.2</VorticeWindowsVersion>
  </PropertyGroup>

  <PropertyGroup>
    <PackageLicenseUrl>https://raw.githubusercontent.com/DawnestOfBread/veldrid/master/LICENSE</PackageLicenseUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <Copyright>Copyright 2020 (c) Eric Mellino. All rights reserved.</Copyright>
    <Authors>Eric Mellino, DawnestOfBread</Authors>
    <RepositoryUrl>https://github.com/DawnestOfBread/veldrid</RepositoryUrl>
  </PropertyGroup>

  <PropertyGroup>
    <NativeLibDirectory>$(MSBuildThisFileDirectory)native/</NativeLibDirectory>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)Intermediate\$(MSBuildProjectName)</BaseIntermediateOutputPath>
    <IntermediateOutputPath>$(BaseIntermediateOutputPath)</IntermediateOutputPath>
    <MSBUildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBUildProjectExtensionsPath>

    <BuildPath>$(MSBuildThisFileDirectory)Build</BuildPath>
    <BaseOutputPath>$(BuildPath)\$(ConfigurationProfile)</BaseOutputPath>
    <OutputPath>$(BaseOutputPath)\$(MSBuildProjectName)</OutputPath>
    <PackageOutputPath>$(MSBuildThisFileDirectory)\Packages</PackageOutputPath>
  </PropertyGroup>

  <PropertyGroup>
    <IsWindows Condition="'$(OS)' == 'Windows_NT'">true</IsWindows>
    <IsMacOS Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))' == 'true'">true</IsMacOS>
    <IsLinux Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))' == 'true'">true</IsLinux>
  </PropertyGroup>

  <PropertyGroup>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.1.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup>
    <NerdbankGitVersioningVersion>3.4.255</NerdbankGitVersioningVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Version="$(NerdbankGitVersioningVersion)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
